### ISSUE TITLE
Deal with php-fig/log-util#4 and php-fig/log-util#6

### ISSUE THREAD

**Issue by ralflang** [php-fig/log-test#1]
Now that the new repo is created, follow-up tasks are required.

A two-week voting process on release of version 1.0 of fig/log-test has been started and looks promising. This would accompany the psr/log 1.1 package.

Once this is actually release, we need to deal with 

php-fig/log-util#4 - Issue on Setup strategy by @GromNaN 
and 
php-fig/log-util#6 - v1.1 - Pull Request on  "import classes from psr/log 1.1, compatible with psr/log 2.0 and 3.0" also by @GromNaN.

@GromNaN would you like to re-do your PR against this Repo or should I try to piece together the necessary delta? Sorry for making you wait so long.

**Comment by GromNaN** [comment]
Hi! I'm thrilled to see activity on this small package.
I recreated the PR for 1.1: https://github.com/php-fig/log-test/pull/2
