### ISSUE TITLE
New release to support psr/log 2.* and 3.*

### ISSUE THREAD

**Issue by mvanduijker** [php-fig/log-test#4]
Can a new release be made so we can use this in conjunction with psr/log > 1.x?

**Comment by ralflang** [comment]
Yes. Most likely next monday.
See 
- https://github.com/php-fig/log-test/pull/2#issuecomment-1272999297 
- https://groups.google.com/g/php-fig/c/V1sUryh3c4c

**Comment by ralflang** [comment]
Released.
